# Generated by Django 5.0.3 on 2024-05-16 19:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('visualisado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CrearQR',
            fields=[
                ('total', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_p', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tip_doc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=2)),
                ('correo', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener números.', regex='^[0-9]*$')])),
                ('rol_u', models.CharField(choices=[('Adm', 'Administrador'), ('Estud', 'Estudiante'), ('Ext', 'Externo')], max_length=50)),
                ('carrera', models.CharField(blank=True, choices=[('IS', 'Ingeniería de Sistemas'), ('IA', 'Ingeniería Ambiental'), ('IAG', 'Ingeniería Agronómica'), ('AD', 'Administración de Empresas'), ('CP', 'Contaduría Pública')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=40)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('color', models.CharField(max_length=7)),
                ('descripcion', models.CharField(max_length=100)),
                ('assigned', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('encrypted_data', models.TextField()),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_assigned', models.BooleanField(default=False)),
                ('computador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.computador')),
                ('create_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.computador')),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.qrcode')),
            ],
            options={
                'unique_together': {('computador', 'qrcode')},
            },
        ),
    ]
